environment: prod
location: eastus2

management_groups:
  enabled: true
  root_id: contoso
  prefix: caf-prod
  topology: platform

policy:
  enabled: true
  enable_security_baseline: true
  enable_backup: true
  enable_tag_policy: true

logging_monitoring:
  enabled: true
  log_analytics_workspace_name: log-prod-landingzone
  retention_days: 365

hub_network:
  enabled: true
  address_space: 10.20.0.0/16
  dns_servers: []
  create_azure_firewall: true
  create_vpn_gateway: true
  create_er_gateway: true

shared_services:
  enabled: true
  enable_key_vault: true
  enable_automation_account: true

feature_flags:
  create_landing_zone_subscriptions: true
  enable_defender_for_cloud: true
  enable_diagnostics_for_all: true
